name: main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW32
          location: D:\
          install: >-
            mingw-w64-i686-toolchain
            libtool
            automake-wrapper
            autoconf-wrapper
            mingw-w64-i686-tinyxml
            mingw-w64-i686-drmingw
            mingw-w64-i686-wxwidgets3.2-common-libs
            mingw-w64-i686-wxwidgets3.2-common
            mingw-w64-i686-wxwidgets3.2-msw
            mingw-w64-i686-wxwidgets3.2-msw-libs
            mingw-w64-i686-wxwidgets3.2-msw-cb_headers
            base-devel
            zip
            git
            p7zip
            mingw-w64-i686-hunspell
            mingw-w64-i686-boost

      - name: build codeblocks
        id: build
        shell: msys2 {0}
        run: |
          .ci/build.sh
          7zr a -mx9 -mqs=on -mmt=on /opt/codeblocks.7z /opt/codeblocks/*
          
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ steps.build.outputs.RELEASE_TAG }}
          name: ${{ steps.build.outputs.RELEASE_NAME }}
          artifacts: "D:/msys64/opt/codeblocks.7z"
          body: |
            This is ${{ steps.build.outputs.RELEASE_NAME }}. Please read the instructions first.
          token: ${{ secrets.GITHUB_TOKEN }}
